name: build-and-deploy

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    name: build and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: install mdbook
        uses: taiki-e/install-action@v2
        with:
          tool: mdbook

      - run: mdbook build

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
